services:
  graphql_postgres:
    image: gangstead/postgis:13-3.1-arm
    container_name: "graphql_postgres"
    environment:
      POSTGRES_DB: "shop_db"
      POSTGRES_USER: "shop_admin"
      POSTGRES_PASSWORD: "shop_password"
    ports:
      - "5437:5432"
    command: postgres -c fsync=off -c synchronous_commit=off -c full_page_writes=off
