# Generated by Django 4.0.5 on 2022-06-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogue", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productattribute",
            name="option_group",
        ),
        migrations.RemoveField(
            model_name="productattributevalue",
            name="entity_content_type",
        ),
        migrations.RemoveField(
            model_name="productattributevalue",
            name="entity_object_id",
        ),
        migrations.RemoveField(
            model_name="productattributevalue",
            name="value_file",
        ),
        migrations.RemoveField(
            model_name="productattributevalue",
            name="value_image",
        ),
        migrations.RemoveField(
            model_name="productattributevalue",
            name="value_multi_option",
        ),
        migrations.RemoveField(
            model_name="productattributevalue",
            name="value_option",
        ),
        migrations.AlterField(
            model_name="productattribute",
            name="type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("integer", "Integer"),
                    ("boolean", "True / False"),
                    ("float", "Float"),
                    ("richtext", "Rich Text"),
                    ("date", "Date"),
                    ("datetime", "Datetime"),
                ],
                default="text",
                max_length=20,
                verbose_name="Type",
            ),
        ),
        migrations.DeleteModel(
            name="AttributeOption",
        ),
        migrations.DeleteModel(
            name="AttributeOptionGroup",
        ),
    ]
