# Generated by Django 4.0.5 on 2022-06-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_producttype_options_alter_product_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='upc',
            field=models.CharField(max_length=255, unique=True, verbose_name='Product upc'),
        ),
    ]
